version: "3.9"
   
services:
  web:
    container_name: photo_gallery
    build: .
    command: bash -c "
      python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
